model:
  name: "mistralai/Mistral-7B-v0.1"
  torch_dtype: "float16"
  device_map: "auto"

data:
  dataset_name: "wikitext"
  dataset_config: "wikitext-2-raw-v1"
  block_size: 128
  train_subset_size:
  eval_subset_size:

training:
  output_dir: "full_finetuning/output_vanilla_finetuned"
  results_logging: "full_finetuning/logs"
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 8
  max_grad_norm: 0.5
  num_train_epochs: 3
  save_steps: 1000
  logging_steps: 500
  learning_rate: 1e-6
  optim: "adafactor"
  fp16: false
  bf16: true
  save_strategy: "epoch"
  evaluation_strategy: "epoch"
  load_best_model_at_end: true

generation:
  max_new_tokens: 100
  temperature: 0.7
  top_p: 0.9
  test_prompt: "In a shocking discovery,"

